export const INITIATE_FETCH_WEATHER_DETAILS_DATA =
  "INITIATE_FETCH_WEATHER_DETAILS_DATA";
export const START_FETCH_WEATHER_DETAILS_DATA =
  "START_FETCH_WEATHER_DETAILS_DATA";
export const SUCCESS_FETCH_WEATHER_DETAILS_DATA =
  "SUCCESS_FETCH_WEATHER_DETAILS_DATA";
export const FAIL_FETCH_WEATHER_DETAILS_DATA =
  "FAIL_FETCH_WEATHER_DETAILS_DATA";
