export const INITIATE_FETCH_WEATHER_DETAILS = "INITIATE_FETCH_WEATHER_DETAILS";
export const START_FETCH_WEATHER_DETAILS = "START_FETCH_WEATHER_DETAILS";
export const SUCCESS_FETCH_WEATHER_DETAILS = "SUCCESS_FETCH_WEATHER_DETAILS";
export const FAIL_FETCH_WEATHER_DETAILS = "FAIL_FETCH_WEATHER_DETAILS";

export const SHOW_WEATHER_DETAILS_FOR_SELECTED_DAY =
  "SHOW_WEATHER_DETAILS_FOR_SELECTED_DAY";
